name: 'Jinja2 Engine Repo'
description: 'Use the Jinja2 templating engine on multiple files'
author: 'fletort'
branding:
  icon: 'sliders'
  color: 'red'
inputs:
  variables:
    description:
      'Key, value pairs in .env file format (key=value)'
    required: false
    default: ''
  keep_template:
    description:
      'Put to `true` to keep original template file.'
    default: false
runs:
  using: 'composite'
  steps:
    - name: "Manage Dynamic Template"
      shell: bash
      run: |
        # Need to export multiline variables input and context to pass it to python script
        mkdir ${{ runner.temp }}/build_logs
        echo '${{ inputs.variables }}' > ${{ runner.temp }}/build_logs/inputs_variables.env
        echo '${{ toJson(github) }}' > ${{ runner.temp }}/build_logs/github.json
        echo '${{ toJson(job) }}' > ${{ runner.temp }}/build_logs/job.json
        echo '${{ toJson(runner) }}' > ${{ runner.temp }}/build_logs/runner.json
        echo '${{ toJson(strategy) }}' > ${{ runner.temp }}/build_logs/strategy.json
        echo '${{ toJson(matrix) }}' > ${{ runner.temp }}/build_logs/matrix.json
        pip install -r ${{github.action_path}}/requirements.txt
        keep_template=""
        if [[ "${{inputs.keep_template}}" == "true" ]]; then keep_template="--keep_template"; fi
        python3 ${{github.action_path}}/entrypoint.py ${keep_template} \
          --var_file ${{ runner.temp }}/build_logs/inputs_variables.env \
          --context ${{ runner.temp }}/build_logs/github.json \
          --context ${{ runner.temp }}/build_logs/job.json \
          --context ${{ runner.temp }}/build_logs/runner.json \
          --context ${{ runner.temp }}/build_logs/strategy.json \
          --context ${{ runner.temp }}/build_logs/matrix.json
