name: 'Jinja2 Engine Repo'
description: 'Use the Jinja2 templating engine on multiple files'
author: 'fletort'
branding:
  icon: 'sliders'
  color: 'red'
inputs:
  variables:
    description:
      'Key, value pairs in .env file format (key=value)'
    required: false
    default: ''
  keep_template:
    description:
      'Put to `true` to keep original template file.'
    default: false
runs:
  using: 'composite'
  steps:
    - name: "Manage Dynamic Template"
      shell: bash
      run: |
        # Need to export multiline variables input to pass it to python script
        export INPUT_VARIABLES="${{ inputs.variables }}"
        pip install -r ${{github.action_path}}/requirements.txt
        keep_template=""
        if [[ "${{inputs.keep_template}}" == "true" ]]; then keep_template="--keep_template"; fi
        python3 ${{github.action_path}}/entrypoint.py ${keep_template}
