name: 'Jinja2 Engine Repo'
description: 'Use the Jinja2 templating engine on multiple files'
author: 'fletort'
branding:
  icon: 'sliders'
  color: 'red'
# inputs:
#   templates_mask:
#     description:
#       'Mask Used to detect templates files'
#     default: '*.j2'
runs:
  using: 'composite'
  steps:
    - name: "Manage Dynamic Template"
      shell: bash
      run: |
        pip install jinja2-cli
        python3 ${{github.action_path}}/action/main.py
